#include "Transliter.h"

//TransliterInstance::TransliterInstance()
//{
//    words.insert( QString( "а"), QString("a"));
//    words.insert( QString( "б"), QString("b"));
//    words.insert( QString( "в"), QString("v"));
//    words.insert( QString( "г"), QString("g"));
//    words.insert( QString( "д"), QString("d"));
//    words.insert( QString( "е"), QString("e"));
//    words.insert( QString( "ё"), QString("yo"));
//    words.insert( QString( "ж"), QString("zh"));
//    words.insert( QString( "з"), QString("z"));
//    words.insert( QString( "и"), QString("i"));
//    words.insert( QString( "й"), QString("j"));
//    words.insert( QString( "к"), QString("k"));
//    words.insert( QString( "л"), QString("l"));
//    words.insert( QString( "м"), QString("m"));
//    words.insert( QString( "н"), QString("n"));
//    words.insert( QString( "о"), QString("o"));
//    words.insert( QString( "п"), QString("p"));
//    words.insert( QString( "р"), QString("r"));
//    words.insert( QString( "с"), QString("s"));
//    words.insert( QString( "т"), QString("t"));
//    words.insert( QString( "у"), QString("u"));
//    words.insert( QString( "ф"), QString("f"));
//    words.insert( QString( "х"), QString("h"));
//    words.insert( QString( "ц"), QString("c"));
//    words.insert( QString( "ч"), QString("ch"));
//    words.insert( QString( "ш"), QString("sh"));
//    words.insert( QString( "щ"), QString("sch"));
//    words.insert( QString( "ъ"), QString("j"));
//    words.insert( QString( "ы"), QString("i"));
//    words.insert( QString( "ь"), QString("j"));
//    words.insert( QString( "э"), QString("e"));
//    words.insert( QString( "ю"), QString("yu"));
//    words.insert( QString( "я"), QString("ya"));
//    words.insert( QString( "А"), QString("A"));
//    words.insert( QString( "Б"), QString("B"));
//    words.insert( QString( "В"), QString("V"));
//    words.insert( QString( "Г"), QString("G"));
//    words.insert( QString( "Д"), QString("D"));
//    words.insert( QString( "Е"), QString("E"));
//    words.insert( QString( "Ё"), QString("Yo"));
//    words.insert( QString( "Ж"), QString("Zh"));
//    words.insert( QString( "З"), QString("Z"));
//    words.insert( QString( "И"), QString("I"));
//    words.insert( QString( "Й"), QString("J"));
//    words.insert( QString( "К"), QString("K"));
//    words.insert( QString( "Л"), QString("L"));
//    words.insert( QString( "М"), QString("M"));
//    words.insert( QString( "Н"), QString("N"));
//    words.insert( QString( "О"), QString("O"));
//    words.insert( QString( "Р"), QString("R"));
//    words.insert( QString( "П"), QString("P"));
//    words.insert( QString( "С"), QString("S"));
//    words.insert( QString( "Т"), QString("T"));
//    words.insert( QString( "У"), QString("U"));
//    words.insert( QString( "Ф"), QString("F"));
//    words.insert( QString( "Х"), QString("H"));
//    words.insert( QString( "Ц"), QString("C"));
//    words.insert( QString( "Ч"), QString("Ch"));
//    words.insert( QString( "Ш"), QString("Sh"));
//    words.insert( QString( "Щ"), QString("Sch"));
//    words.insert( QString( "Ъ"), QString("J"));
//    words.insert( QString( "Ы"), QString("I"));
//    words.insert( QString( "Ь"), QString("J"));
//    words.insert( QString( "Э"), QString("E"));
//    words.insert( QString( "Ю"), QString("Yu"));
//    words.insert( QString( "Я"), QString("Ya"));
//}
//extern QMap<QString, QString> words;
QMap<QString, QString> words;
QString Transliter::Translate(QString source)
{
    QMapIterator<QString, QString> i(words);

    while (i.hasNext()) {
        i.next();
        source = source.replace( i.key(), i.value());
    }
    return source;

}
void initTransliter(){
    words.insert( QString( "а"), QString("a"));
    words.insert( QString( "б"), QString("b"));
    words.insert( QString( "в"), QString("v"));
    words.insert( QString( "г"), QString("g"));
    words.insert( QString( "д"), QString("d"));
    words.insert( QString( "е"), QString("e"));
    words.insert( QString( "ё"), QString("yo"));
    words.insert( QString( "ж"), QString("zh"));
    words.insert( QString( "з"), QString("z"));
    words.insert( QString( "и"), QString("i"));
    words.insert( QString( "й"), QString("j"));
    words.insert( QString( "к"), QString("k"));
    words.insert( QString( "л"), QString("l"));
    words.insert( QString( "м"), QString("m"));
    words.insert( QString( "н"), QString("n"));
    words.insert( QString( "о"), QString("o"));
    words.insert( QString( "п"), QString("p"));
    words.insert( QString( "р"), QString("r"));
    words.insert( QString( "с"), QString("s"));
    words.insert( QString( "т"), QString("t"));
    words.insert( QString( "у"), QString("u"));
    words.insert( QString( "ф"), QString("f"));
    words.insert( QString( "х"), QString("h"));
    words.insert( QString( "ц"), QString("c"));
    words.insert( QString( "ч"), QString("ch"));
    words.insert( QString( "ш"), QString("sh"));
    words.insert( QString( "щ"), QString("sch"));
    words.insert( QString( "ъ"), QString("j"));
    words.insert( QString( "ы"), QString("i"));
    words.insert( QString( "ь"), QString("j"));
    words.insert( QString( "э"), QString("e"));
    words.insert( QString( "ю"), QString("yu"));
    words.insert( QString( "я"), QString("ya"));
    words.insert( QString( "А"), QString("A"));
    words.insert( QString( "Б"), QString("B"));
    words.insert( QString( "В"), QString("V"));
    words.insert( QString( "Г"), QString("G"));
    words.insert( QString( "Д"), QString("D"));
    words.insert( QString( "Е"), QString("E"));
    words.insert( QString( "Ё"), QString("Yo"));
    words.insert( QString( "Ж"), QString("Zh"));
    words.insert( QString( "З"), QString("Z"));
    words.insert( QString( "И"), QString("I"));
    words.insert( QString( "Й"), QString("J"));
    words.insert( QString( "К"), QString("K"));
    words.insert( QString( "Л"), QString("L"));
    words.insert( QString( "М"), QString("M"));
    words.insert( QString( "Н"), QString("N"));
    words.insert( QString( "О"), QString("O"));
    words.insert( QString( "Р"), QString("R"));
    words.insert( QString( "П"), QString("P"));
    words.insert( QString( "С"), QString("S"));
    words.insert( QString( "Т"), QString("T"));
    words.insert( QString( "У"), QString("U"));
    words.insert( QString( "Ф"), QString("F"));
    words.insert( QString( "Х"), QString("H"));
    words.insert( QString( "Ц"), QString("C"));
    words.insert( QString( "Ч"), QString("Ch"));
    words.insert( QString( "Ш"), QString("Sh"));
    words.insert( QString( "Щ"), QString("Sch"));
    words.insert( QString( "Ъ"), QString("J"));
    words.insert( QString( "Ы"), QString("I"));
    words.insert( QString( "Ь"), QString("J"));
    words.insert( QString( "Э"), QString("E"));
    words.insert( QString( "Ю"), QString("Yu"));
    words.insert( QString( "Я"), QString("Ya"));
}
